# Name of your application. Used to uniquely configure containers.
service: waitlist_app

# Name of the container image (use your-user/app-name on external registries).
image: waitlist_app

# Deploy to these servers.
servers:
  web:
    - 192.168.0.1

# Enable SSL auto certification via Let's Encrypt
proxy:
  ssl: true
  host: app.example.com

# Where you keep your container images.
registry:
  server: localhost:5555

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
    - SENTRY_DSN
    - SMTP_ADDRESS
  clear:
    # Run the Solid Queue Supervisor inside the web server's Puma process to do jobs.
    SOLID_QUEUE_IN_PUMA: true

    # Set number of cores available to the application on each server.
    WEB_CONCURRENCY: 2
    RAILS_MAX_THREADS: 3

    # Application host for URLs
    APP_HOST: app.example.com

# Aliases are triggered with "bin/kamal <alias>".
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

# Use a persistent storage volume for sqlite database files and local Active Storage files.
volumes:
  - "waitlist_app_storage:/rails/storage"

# Bridge fingerprinted assets between versions.
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: amd64
