production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

  process_analytics:
    class: ProcessAnalyticsJob
    queue: analytics
    schedule: at 2am every day

  sqlite_maintenance:
    class: SqliteMaintenanceJob
    queue: analytics
    schedule: at 3am every day

  flush_page_views:
    class: FlushPageViewsJob
    queue: analytics
    schedule: every 5 minutes

  cleanup_sessions:
    class: CleanupSessionsJob
    queue: analytics
    schedule: at 4am every day
